HogaresVictoria/Models/Contacto.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HogaresVictoria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public int ID { get; set; }
        public string Calle { get; set; }
        public string Nextel { get; set; }
        public string Cell { get; set; }
        public string Horario { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Twitter { get; set; }
        public string Facebook { get; set; }
        public string Colonia { get; set; }
        public string Persona { get; set; }
        public string QuienesSomos { get; set; }
    }
}

HogaresVictoria/Models/Estado.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HogaresVictoria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estado()
        {
            this.Hogares = new HashSet<Hogares>();
        }
    
        public int IDEstado { get; set; }
        public string NombreEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hogares> Hogares { get; set; }
    }
}

HogaresVictoria/Models/Hogares.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HogaresVictoria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hogares
    {
        public int ID { get; set; }
        public Nullable<int> IDTipo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IDEstado { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<int> Precio { get; set; }
        public string ShortDescription { get; set; }
        public string PrimaryImage { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Tipos Tipos { get; set; }
    }
}

HogaresVictoria/Models/HogaresVictoria.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HogaresVictoria.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HogaresVictoriaEntities : DbContext
    {
        public HogaresVictoriaEntities()
            : base("name=HogaresVictoriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contacto> Contacto { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Hogares> Hogares { get; set; }
        public virtual DbSet<Tipos> Tipos { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}

HogaresVictoria/Models/HogaresVictoria.Designer.cs
// T4 code generation is enabled for model 'C:\Users\Chuy\documents\visual studio 2015\Projects\HogaresVictoria\HogaresVictoria\Models\HogaresVictoria.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

HogaresVictoria/Models/HogaresVictoria.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

HogaresVictoria/Models/Tipos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HogaresVictoria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipos()
        {
            this.Hogares = new HashSet<Hogares>();
        }
    
        public int IDTipo { get; set; }
        public string NombreTipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hogares> Hogares { get; set; }
    }
}

HogaresVictoria/Models/Usuarios.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HogaresVictoria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Rol { get; set; }
    }
}

HogaresVictoria/Controllers/InController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HogaresVictoria.Models;

namespace HogaresVictoria.Controllers
{
    public class InController : Controller
    {
        private HogaresVictoriaEntities DB = new HogaresVictoriaEntities();

        // GET: Inicio
        public ActionResult Index()
        {
            var Lastest = DB.Hogares.OrderByDescending(x => x.ID).Take(5).ToList();
            return View(Lastest);
        }

        public ActionResult Contacto()
        {
            return View(DB.Contacto.ToList());
        }

        public ActionResult Casas() {
            var datos = DB.Hogares.Where(x => x.IDTipo == 1).ToList();
            return View(datos);
        }

        //get locales en renta from db
        public ActionResult Locales()
        {
            return View(DB.Hogares.Where(x => x.IDTipo == 2).ToList());
        }
        
        //Get terrenos from db
        public ActionResult Terrenos()
        {
            return View(DB.Hogares.Where(x => x.IDTipo == 3).ToList());
        }

    }
}

HogaresVictoria/Views/In/Casas.cshtml
@model List<HogaresVictoria.Models.Hogares>

@{
    ViewBag.Title = "Casas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Casas</h2>
<hr />
@foreach (var item in Model)
{
    @Html.DisplayFor(x => item.Ubicacion)<br />
    @Html.DisplayFor(x => item.ShortDescription)<br />
    @Html.DisplayFor(x => item.Precio)<br />
    @Html.DisplayFor(x => item.Tipos.NombreTipo)
    <br />
    <br />
}

HogaresVictoria/Views/In/Contacto.cshtml
@model IEnumerable<HogaresVictoria.Models.Contacto>

@{
    ViewBag.Title = "Contacto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Contacto</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Calle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nextel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cell)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Horario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Twitter)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Facebook)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Colonia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Persona)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Calle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nextel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cell)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Horario)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Twitter)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Facebook)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Colonia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Persona)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

HogaresVictoria/Views/In/Index.cshtml
@model List<HogaresVictoria.Models.Hogares>


@{
    ViewBag.Title = ".:: Hogares Victoria ::.";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="text-center">HogaresVictoria</h2>

<ul class="pgwSlider">
    <li><img src="http://lorempixel.com/960/520/city" alt="Paris, France" data-description="Eiffel Tower and Champ de Mars <span class='glyphicon glyphicon-eye-open'></span>"></li>
    <li><img src="http://lorempixel.com/960/520/business" alt="Montréal, QC, Canada" /></li>
    <li>
        <img src="http://lorempixel.com/960/520/nature">
        <span>Shanghai, China</span>
    </li>
    <li>
        <a href="http://www.nyc.gov" target="_blank">
            <img src="http://lorempixel.com/960/520/people">
            <span>New York, NY, USA</span>
        </a>
    </li>
</ul>


<br />


<ul>
    @foreach (var item in Model)
    {
        <li>@Html.DisplayFor(x => item.Tipos.NombreTipo) - @Html.DisplayFor(x => item.Estado.NombreEstado)</li>
        <li>@Html.DisplayFor(x => item.Ubicacion) - $@Html.DisplayFor(x => item.Precio)</li>
        <li>@Html.DisplayFor(x => item.ShortDescription)</li>
        <br />
        <br />
    }
</ul>

HogaresVictoria/Views/In/Locales.cshtml
@model List<HogaresVictoria.Models.Hogares>

@{
    ViewBag.Title = "Locales";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Locales</h2>
<hr />
<br />
@foreach (var item in Model)
{
    @Html.DisplayFor(x => item.Ubicacion)<br />
    @Html.DisplayFor(x => item.ShortDescription)<br />
    @Html.DisplayFor(x => item.Precio)<br />
    @Html.DisplayFor(x => item.Tipos.NombreTipo)
    <br />
    <br />
}

HogaresVictoria/Views/In/Terrenos.cshtml
@model List<HogaresVictoria.Models.Hogares>

@{
    ViewBag.Title = "Terrenos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Terrenos</h2>
<hr />
<br />
@foreach (var item in Model)
{
    @Html.DisplayFor(x => item.Ubicacion)<br />
    @Html.DisplayFor(x => item.ShortDescription)<br />
    @Html.DisplayFor(x => item.Precio)<br />
    @Html.DisplayFor(x => item.Tipos.NombreTipo)
    <br />
    <br />
}

HogaresVictoria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/pgwslider.min.css" rel="stylesheet" type="text/css" />
    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Hogares Victoria", "", "In", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse navbar-right">
                <ul class="nav navbar-nav">
                    <li class="navbar-left">
                        @Html.ActionLink("Casas","Casas", "In")
                    </li>
                    <li class="navbar-left">
                        @Html.ActionLink("Locales/Oficinas", "Locales", "In")
                    </li>
                    <li class="navbar-left">
                        @Html.ActionLink("Terrenos", "Terrenos", "In")
                    </li>
                    <li class="navbar-left">
                        @Html.ActionLink("Contacto", "Contacto", "In")
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />

       
        <footer>
                <p>La dirección de la empresa -</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-2.2.2.min.js" type="text/javascript"></script>
    <script src="~/Scripts/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/Scripts/pgwslider.min.js" type="text/javascript"></script>
    <script type="text/javascript">
    $(document).ready(function ( ) {
        $('.pgwSlider').pgwSlider({
            listPosition: "right",
            selectionMode: "click",
            transitionEffect: "fading",
            autoSlide: true,
            displayList: true,
            verticalCentering: true,
            adaptiveHeight: false,
            transitionDuration: 1400,
            intervalDuration: 2500

        });
    });
    </script>
</body>
</html>